"""Add autoincrement to models id

Revision ID: 3a9c6c477c94
Revises: f3339d1cb42e
Create Date: 2022-10-16 15:47:21.476042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a9c6c477c94'
down_revision = 'f3339d1cb42e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
