"""Add field is_active to model Reservation

Revision ID: 5d50ab984d33
Revises: c1c3af16128b
Create Date: 2022-11-22 22:20:00.911785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d50ab984d33'
down_revision = 'c1c3af16128b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservations', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservations', 'is_active')
    # ### end Alembic commands ###
