"""Add table PlaceType

Revision ID: c1c3af16128b
Revises: 3a9c6c477c94
Create Date: 2022-11-02 19:36:40.789105

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c1c3af16128b'
down_revision = '3a9c6c477c94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('place_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('places', sa.Column('place_type_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'places', 'place_types', ['place_type_id'], ['id'])
    op.drop_column('places', 'type_place')
    op.alter_column('reservations', 'date_reservation',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reservations', 'date_reservation',
               existing_type=sa.DATE(),
               nullable=True)
    op.add_column('places', sa.Column('type_place', postgresql.ENUM('CAFE', 'BAR', 'RESTAURANT', name='placetype'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'places', type_='foreignkey')
    op.drop_column('places', 'place_type_id')
    op.drop_table('place_types')
    # ### end Alembic commands ###
